www/account/urls.py
from django.conf.urls import url

from account import views

app_name = 'account'
urlpatterns = [
    url(r'^register$', views.Register.as_view(), name='register'),
    url(r'^login$', views.Login.as_view(), name='login'),
    url(r'^reset$', views.PasswordReset.as_view(), name='reset'),
    url(r'^reset/done$', views.PasswordResetDone.as_view(),
        name='reset_done'),
    url(r'^profile/(?P<user_id>\d+)$', views.profile, name='profile'),
    url(r'^my_profile/$', views.my_profile, name='my_profile'),
    url(r'^notifications$', views.Notifications.as_view(), name='notifications'),
    url(r'^logout', views.my_logout, name='logout'),
    url(r'^notifications/seen/(?P<id>\d+)$', views.SeenNotification.as_view(), name='seen_notif'),
    url(r'^user/change_permission$', views.ChangePermissionList.as_view(), name='change_perm_list'),
    url(r'^user/activate/(?P<uidb64>[^/]+)/(?P<token>[^/]+)$', views.ActivateUser.as_view(), name='activate'),
    url(r'^user/change_permission/(?P<id>[^/]+)/(?P<action>[^/]+)$', views.ChangePermission.as_view(),
        name='change_perm')
]

www/blog/urls.py
from django.conf.urls import url
from blog import views

app_name = 'blog'
urlpatterns = [
    url(r'^post/(?P<post_id>\d+)$', views.show_post, name='show_post'),
    url(r'^add-post$', views.AddPostView.as_view(), name='add_post'),
    url(r'^tag/add/(?P<post_id>\d+)$', views.AddTagView.as_view(), name='add_tag'),
    url(r'^like/(?P<post_id>\d+)$', views.LikeView.as_view(), name='like'),
    url(r'^dislike/(?P<post_id>\d+)$', views.DislikeView.as_view(), name='dislike'),
    url(r'^delete/(?P<post_id>\d+)$', views.DeleteView.as_view(), name='delete'),
    url(r'^report/(?P<post_id>\d+)$', views.ReportView.as_view(), name='report'),
]

www/www/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import account
from account import urls as account_urls
from website import urls as website_urls
from blog import urls as blog_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^account/', include(account_urls)),
    url(r'^blog/', include(blog_urls)),
    url(r'^', include(website_urls)),
                  url(
        r'^account/reset/confirm/(?P<uidb64>[^/]+)/(?P<token>[^/]+)/$',
        account.views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
] +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

www/templates/base.html
{% load static %}
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<!DOCTYPE html>
<html lang="fa">
<head>
    <title>Tehran ACM WWW</title>
    <meta content="text/html" charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="



            {% if LANGUAGE_BIDI %}{% static 'semantic/semantic.rtl.min.css' %}{% else %}{% static 'semantic/semantic.min.css' %}{% endif %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'semantic/semantic.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

    {% block extra_header %}{% endblock %}
</head>
<body {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>

<div class="ui attached fluid menu segment" style="margin: 0 !important;">

        <a class="item" href="/">
            خانه
        </a>

    <div class="right menu">
        {% if request.user.is_authenticated %}
            <a class="item" href="{% url 'account:profile' request.user.id %}">
                <img class="ui avatar image" src="{{ request.user.profile.avatar.url }}">
                {{ request.user.username }}
            </a>
            <a class="item" href="{% url 'blog:add_post' %}">
            افزودن نوشته
            </a>
            <a class="item" href="{% url 'account:notifications' %}">
            اعلان ها
            </a>

            <a class="item" href="{% url 'account:logout' %}">
                خروج
            </a>
        {% else %}
            <a class="ui item" href="{% url 'account:register' %}">
                ثبت نام
            </a>
            <a class="ui item" href="{% url 'account:login' %}">
                ورود
            </a>
        {% endif %}

    </div>
</div>

<div>

    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="ui {% if message.tags %}{{ message.tags }}{% endif %} message">
                    <p>{{ message }}</p>
                </div>
            {% endfor %}

        </div>
    {% endif %}
</div>
{% block body %}

{% endblock %}

{% block footer_scripts %}{% endblock %}

<script src="{% static 'js/jquery.inview.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>