www/account/urls.py
from django.conf.urls import url

from account import views

app_name = 'account'
urlpatterns = [
    url(r'^register$', views.Register.as_view(), name='register'),
    url(r'^login$', views.Login.as_view(), name='login'),
    url(r'^reset$', views.PasswordReset.as_view(), name='reset'),
    url(r'^reset/done$', views.PasswordResetDone.as_view(),
        name='reset_done'),
    url(r'^profile/(?P<user_id>\d+)$', views.profile, name='profile'),
    url(r'^my_profile/$', views.my_profile, name='my_profile'),
    url(r'^notifications$', views.Notifications.as_view(), name='notifications'),
    url(r'^logout', views.my_logout, name='logout'),
    url(r'^notifications/seen/(?P<id>\d+)$', views.SeenNotification.as_view(), name='seen_notif'),
    url(r'^user/change_permission$', views.ChangePermissionList.as_view(), name='change_perm_list'),
    url(r'^user/activate/(?P<uidb64>[^/]+)/(?P<token>[^/]+)$', views.ActivateUser.as_view(), name='activate'),
    url(r'^user/change_permission/(?P<id>[^/]+)/(?P<action>[^/]+)$', views.ChangePermission.as_view(),
        name='change_perm')
]

www/blog/urls.py
from django.conf.urls import url
from blog import views

app_name = 'blog'
urlpatterns = [
    url(r'^post/(?P<post_id>\d+)$', views.show_post, name='show_post'),
    url(r'^add-post$', views.AddPostView.as_view(), name='add_post'),
    url(r'^tag/add/(?P<post_id>\d+)$', views.AddTagView.as_view(), name='add_tag'),
    url(r'^like/(?P<post_id>\d+)$', views.LikeView.as_view(), name='like'),
    url(r'^dislike/(?P<post_id>\d+)$', views.DislikeView.as_view(), name='dislike'),
    url(r'^delete/(?P<post_id>\d+)$', views.DeleteView.as_view(), name='delete'),
    url(r'^report/(?P<post_id>\d+)$', views.ReportView.as_view(), name='report'),
]

www/www/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import account
from account import urls as account_urls
from website import urls as website_urls
from blog import urls as blog_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^account/', include(account_urls)),
    url(r'^blog/', include(blog_urls)),
    url(r'^', include(website_urls)),
                  url(
        r'^account/reset/confirm/(?P<uidb64>[^/]+)/(?P<token>[^/]+)/$',
        account.views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
] +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

www/blog/models.py
from django.contrib.auth.models import User
from django.db import models

from website import jalali


class Post(models.Model):
    title = models.CharField(max_length=256, null=True, blank=True)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    tags = models.ManyToManyField(to='Tag', related_name='tagged_items', null=True, blank=True)
    time = models.DateTimeField(auto_now_add=True)
    anon = models.BooleanField(verbose_name='ناشناس', default=False)

    def get_likes_count(self):
        return UserLikesPost.objects.filter(post=self).count()

    def get_dislikes_count(self):
        return UserDislikesPost.objects.filter(post=self).count()

    def get_comments_count(self):
        return Comment.objects.filter(post=self).count()

    def get_time(self):
        return jalali.Gregorian(str(self.time).split(' ')[0]).persian_string()


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    text = models.CharField(max_length=1024)
    time = models.DateTimeField(auto_now_add=True)


class UserLikesPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class UserDislikesPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class ReportPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Tag(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

www/blog/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from blog.models import Post, Tag


class NewCommentForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea, max_length=1000, label='متن نظر')


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['tags', 'author']


class AddTagToPostForm(forms.Form):
    tag = forms.ModelChoiceField(label='تگ', queryset=Tag.objects.all())

www/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User, AnonymousUser
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import FormView

from account.models import Notification
from blog.forms import NewCommentForm, AddPostForm
from blog.forms import NewCommentForm, AddPostForm, AddTagToPostForm
from blog.models import Post, Comment, UserLikesPost, UserDislikesPost, Tag
from blog.models import Post, Comment, UserLikesPost, UserDislikesPost, ReportPost


def show_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    add_tag_form = AddTagToPostForm()
    if request.method == 'POST':
        comment = Comment()
        comment.user = request.user
        comment.post = post
        comment.text = request.POST.get('text')
        comment.save()

        text = comment.text
        mentions = list()
        words = str(text).split()
        for word in words:
            if word[0] == '@':
                if User.objects.filter(username=word[1:]).exists():
                    user = User.objects.filter(username=word[1:]).first()
                    notif = Notification()
                    notif.text = 'شما در پست جدیدی منشن شده اید' + \
                                 '<a class="ui animated small right floated button" href="' + reverse('blog:show_post',
                                                                                                      args=[
                                                                                                          post_id]) + '">' \
                                 + '<div class="visible content">' + 'مشاهده پست' + '</div>' \
                                 + '<div class="hidden content"> \
                                    <i class="right arrow icon"></i> \
                                    </div>' + '</a>'
                    notif.user = user
                    notif.seen = False
                    notif.save()

    comments = Comment.objects.filter(post=post)
    return render(request, 'blog/single_post.html', {
        'post': post,
        'comments': comments,
        'new_comment_form': NewCommentForm(),
        'add_tag_form': add_tag_form
    })


class LikeView(View, LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        id = self.kwargs['post_id']

        if not UserLikesPost.objects.filter(post_id=id, user=self.request.user).exists():
            l = UserLikesPost(user=self.request.user)
            l.post_id = id
            l.save()
        return HttpResponseRedirect(reverse('blog:show_post', args=[id]))


class DislikeView(View, LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        id = self.kwargs['post_id']

        if not UserDislikesPost.objects.filter(post_id=id, user=self.request.user).exists():
            l = UserDislikesPost(user=self.request.user)
            l.post_id = id
            l.save()
        return HttpResponseRedirect(reverse('blog:show_post', args=[id]))


class DeleteView(View, LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        id = self.kwargs['post_id']

        try:
            p = Post.objects.get(id=id)
            if p.author == self.request.user:
                p.delete()
        except Exception as e:
            print(e)
        return HttpResponseRedirect(reverse('account:my_profile'))


class ReportView(View, LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        id = self.kwargs['post_id']
        try:
            r = ReportPost(user=self.request.user)
            r.post_id = id
            r.save()
        except Exception as e:
            print(e)
        return HttpResponseRedirect(reverse('blog:show_post', args=[id]))


class AddPostView(FormView):
    template_name = 'blog/add_post.html'
    form_class = AddPostForm
    success_url = reverse_lazy('account:my_profile')

    def get_success_url(self):
        if self.anon:
            return reverse_lazy('blog:show_post', args=[self.post_id])
        else:
            return reverse_lazy('account:my_profile')

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()

        self.post_id = post.id
        self.anon = post.anon

        return super(FormView, self).form_valid(form)


class AddTagView(View, LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        id = self.kwargs['post_id']
        try:
            t = Tag.objects.get(id=self.request.POST.get('tag'))
            p = Post.objects.get(id=id)
            p.tags.add(t)
            p.save()
        except Exception as e:
            print(e)
        return HttpResponseRedirect(reverse('blog:show_post', args=[id]))

www/blog/templates/blog/add_post.html
{% extends 'base.html' %}
{% load semanticui %}
{% load static %}

{% block body %}
    <div style="margin: 10% auto; width: 50%">
        <form class="ui form" method="post" action="">
            {#            {% render_form form %}#}
            {#                {{ form.media }}#}
            <div class="field"><label for="id_title">Title</label><input type="text" name="title" maxlength="256"
                                                                         id="id_title"/></div>
            <div class="required field"><label for="id_text">Text</label>
                <style>
                    #editable-shit span {
                        color: blue;
                    }
                </style>
                <div id="editable-shit"
                     style="min-height: 400px; border: 1px solid #ccc; border-radius: 2px; padding: 10px"
                     contenteditable="true">

                </div>
                <textarea name="text" style="display: none" cols="40" rows="10"
                          required id="id_text">
</textarea></div>
            <div class="inline field">
                <div class="ui checkbox"><input type="checkbox" name="anon" style="display:hidden" id="id_anon"/><label
                        for="id_anon">ناشناس</label></div>
            </div>


            {% csrf_token %}
            <div class="submit">
                <button type="submit" class="ui button">ثبت</button>
            </div>
        </form>
    </div>

    <script>
        window.addEventListener('load', function () {
            var tout = null;
            var e = document.getElementById('editable-shit');
            var txt = document.getElementById('id_text');
            e.addEventListener('keypress', function () {
                if (tout != null) {
                    clearTimeout(tout);
                }
                tout = setTimeout(function () {
                    text = e.innerHTML;
                    pure = text.replace(/<[^>]*>/g, "");
                    tagged = pure.replace(/(\#[^\s]+)/, "<span>$1</span>");
                    e.innerHTML = tagged;
                    txt.innerHTML = pure;
                    tout = null;
                    console.log(e.selectionStart);
                }, 1000);


            });
        })
    </script>

{% endblock %}

{% block extra_header %}
    <script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
    {{ block.super }}

{% endblock %}

www/blog/templates/blog/post_list.html
<div class="ui three cards" style="width: 100%;">
    {% for post in blog_posts %}
        <div class="card">
            <div class="content">
                <img class="right floated mini ui image" src="{{ post.author.profile.avatar.url }}">
                <div class="ui small header" style="margin: 0 !important;">
                    <a href="{% url 'account:profile' post.author.id %}">@{{ post.author.username }}</a>
                </div>
                <div class="ui tiny header" style="margin: 0 !important;">
                    {{ post.author.first_name }} در {{ post.get_time }} - {{ post.time|time }}
                </div>
                <div class="description">
                    {% autoescape off %}
                        {{ post.text|truncatewords:40 }}
                    {% endautoescape %}
                </div>
            </div>
            <div class="extra content">
                <div class="ui label">{{ post.get_comments_count }} نظر</div>
                <div class="ui label">{{ post.get_likes_count }} لایک</div>
                <div class="ui label">{{ post.get_dislikes_count }} دیسلایک</div>

                <a class="ui mini icon right floated button" href="{% url 'blog:show_post' post.id %}">
                    <i class="left arrow icon"></i>
                </a>
            </div>
        </div>
    {% endfor %}
</div>

www/blog/templates/blog/single_post.html
{% extends 'base.html' %}
{% load semanticui %}

{% block body %}
    <div class="ui container">
        <div class="ui segment">
            <h1 class="ui header">
                {{ post.title }}
            </h1>
            <div class="meta">
                {% if not post.anon or request.user == post.author %}
                    <a href="{% url 'account:profile' post.author.id %}">
                        نویسنده: {{ post.author }}
                    </a>
                {% else %}
                    <a href="#">
                        کاربر ناشناس
                    </a>
                {% endif %}
            </div>
            <p>
                {% autoescape off %}
                    {{ post.text }}
                {% endautoescape %}
            </p>
        </div>
        <div>
            <div class="ui label">{{ post.get_likes_count }} لایک</div>
            <div class="ui label">{{ post.get_dislikes_count }} دیسلایک</div>
        </div>
        <br><br>
        <div>
            <a class="ui button primary" href="{% url 'blog:like' post_id=post.id %}">
                لایک
            </a>
            <a class="ui primary button"
               href="{% url 'blog:dislike' post_id=post.id %}">دیسلایک
            </a>
            {% if request.user.is_staff or request.user.is_superuser %}
                <a class="ui red button"
                   href="{% url 'blog:report' post_id=post.id %}">ریپورت
                </a>
            {% endif %}
        </div>

        <div><br>
            <h4>تگ‌ها</h4>

            {% for tag in post.tags.all %}
                <div class="ui label">{{ tag }}</div>
            {% endfor %}
        </div>

        {% if request.user.is_staff or request.user.is_superuser %}
            <br><br>
            <div>
                <h2>افزودن تگ</h2>
                <form class="ui form" method="post" action="{% url 'blog:add_tag' post.id %}">
                    {% render_form add_tag_form %}
                    {% csrf_token %}
                    <div class="submit">
                        <button type="submit" class="ui button">افزودن تگ</button>
                    </div>
                </form>
            </div>
        {% endif %}
        <br><br>
        <div>
            {% if post.author == request.user %}
                <a class="ui red button" href="{% url 'blog:delete' post_id=post.id %}">حذف کردن</a>
            {% endif %}
        </div>
        <div class="ui comments">
            <h3 class="ui dividing header">نظرات</h3>
            {% for comment in comments %}
                <div class="comment">
                    <a class="avatar" href="{% url 'account:profile' comment.user.id %}">
                        <img src="{{ comment.user.profile.avatar.url }}">
                    </a>
                </div>
                <div class="content" style="margin: 2px; padding: 0 3px;">
                    <div class="metadata">
                        {{ comment.user.first_name }} (<a class="author"
                                                          href="{% url 'account:profile' comment.user.id %}">{{ comment.user.username }}</a>)
                        در
                        <span class="date">{{ comment.time }}</span>

                    </div>
                    <div class="text">
                        {{ comment.text }}
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if request.user.is_authenticated %}
            <form class="ui form" method="post" action="">
                {% render_form new_comment_form %}
                {% csrf_token %}
                <div class="submit">
                    <button type="submit" class="ui button">ثبت نظر</button>
                </div>

            </form>
        {% endif %}
    </div>
{% endblock %}